version: "3"
services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 8081:8081
    environment:
      - NODE_ENV=production
